// client/src/lib/views/dcg/mods.svelte
<script lang="ts">
	import Paper from '$lib/components/paper.svelte';
	import { get } from './utils/manipulation';

	export let status: any[];
	let mods: string[] = [];

	function getMods(): string[] {
		const mods = get(status, 'saveinfo.mods');
		if (!mods) return [];

		return mods.map((mod: string) => {
			return mod.split('_')[1].split(':')[0];
		});
	}

	$: if (status) {
		mods = getMods();
	}
</script>

{#if mods.length > 0}
	<div class="mt-4">
		<Paper bordered kind="info">
			<div class="p-4">
				<p>The following mods were detected:</p>
				<ul>
					{#each mods as mod}
						<li>
							<a
								href="https://steamcommunity.com/sharedfiles/filedetails/?id={mod}"
								target="_blank"
								rel="noopener noreferrer">{mod}</a
							>
						</li>
					{/each}
				</ul>
			</div>
		</Paper>
	</div>
{/if}

// src/components/react/tools/goh-editor/components/Mods.tsx
import { useMemo } from 'react';
import { get } from '../utils/manipulation';

export default function Mods(props: ModsProps) {
    /**
     * Extracts the mod list and formats it as an array of mod IDs,
     * but only when campaign status changes
     */
    const mods: string[] = useMemo(() => {
		const mods = get(props.status, 'saveinfo.mods');

		if (!mods) return [];

		return mods.map((mod: string) => {
			return mod.split('_')[1].split(':')[0];
		});

    }, [props.status])

    // only show if successful
    if (!mods.length) return null 

    return (
        <div className="mt-4">
            <div className="px-4 border border-neutral-700">
                <div className="p-4">
                    <p>The following mods were detected:</p>
                    <ul>
                        {mods.map((mod, index) => (
                            <li key={index}>
                                <a
                                    href={`https://steamcommunity.com/sharedfiles/filedetails/?id=${mod}`}
                                    target="_blank"
                                    rel="noopener noreferrer">
                                    {mod}
                                </a>
                            </li>
                        ))}
                    </ul>
                </div>
            </div>
        </div>
    )
}

export interface ModsProps {
    status: any 
}
